services:
    app:
        build:
            context: ./docker/8.4
            dockerfile: Dockerfile
        image: 'tbitencourt/php-fpm:8.4'
        container_name: 'assessment-laravel-bank-app'
        ports:
            - "9000:9000"
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '.:/var/www/html'
        networks:
            - app-network
        depends_on:
            - db
    webserver:
        image: 'nginx:alpine'
        container_name: 'assessment-laravel-bank-webserver'
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - './:/var/www/html'
            - './docker/nginx/app.conf:/etc/nginx/conf.d/app.conf'
        networks:
            - app-network
        depends_on:
            - db
    db:
        image: 'mysql/mysql-server:8.0'
        container_name: 'assessment-laravel-bank-db'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'tbitencourt-dbdata:/var/lib/mysql'
        networks:
            - app-network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
networks:
    app-network:
        driver: bridge
volumes:
    tbitencourt-dbdata:
        driver: local
